[tool.poetry]
name = "aspectc-translater"
version = "0.1.0"
description = "Aspect Oriented Programming Language"
authors = ["Ikuya Nagaki"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.8"
pycparser = "^2.21"
lark = "^1.1.8"
pycparser-fake-libc = "^2.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
