#
#  TOPPERS Automotive Kernel
#      Toyohashi Open Platform for Embedded Real-Time Systems
#      Automotive Kernel
# 
#  Copyright (C) 2000-2003 by Embedded and Real-Time Systems Laboratory
#                              Toyohashi Univ. of Technology, JAPAN
#  Copyright (C) 2004-2006 by Witz Corporation, JAPAN
# 
#  上記著作権者は，以下の (1)〜(4) の条件か，Free Software Foundation 
#  によって公表されている GNU General Public License の Version 2 に記
#  述されている条件を満たす場合に限り，本ソフトウェア（本ソフトウェア
#  を改変したものを含む．以下同じ）を使用・複製・改変・再配布（以下，
#  利用と呼ぶ）することを無償で許諾する．
#  (1) 本ソフトウェアをソースコードの形で利用する場合には，上記の著作
#      権表示，この利用条件および下記の無保証規定が，そのままの形でソー
#      スコード中に含まれていること．
#  (2) 本ソフトウェアを，ライブラリ形式など，他のソフトウェア開発に使
#      用できる形で再配布する場合には，再配布に伴うドキュメント（利用
#      者マニュアルなど）に，上記の著作権表示，この利用条件および下記
#      の無保証規定を掲載すること．
#  (3) 本ソフトウェアを，機器に組み込むなど，他のソフトウェア開発に使
#      用できない形で再配布する場合には，次のいずれかの条件を満たすこ
#      と．
#    (a) 再配布に伴うドキュメント（利用者マニュアルなど）に，上記の著
#        作権表示，この利用条件および下記の無保証規定を掲載すること．
#    (b) 再配布の形態を，別に定める方法によって，TOPPERSプロジェクトに
#        報告すること．
#  (4) 本ソフトウェアの利用により直接的または間接的に生じるいかなる損
#      害からも，上記著作権者およびTOPPERSプロジェクトを免責すること．
# 
#  本ソフトウェアは，無保証で提供されているものである．上記著作権者お
#  よびTOPPERSプロジェクトは，本ソフトウェアに関して，その適用可能性も
#  含めて，いかなる保証も行わない．また，本ソフトウェアの利用により直
#  接的または間接的に生じたいかなる損害に関しても，その責任を負わない．
#
#

#
#  Makefile のシステム依存部分
#  （H8S/2638 北斗電子社製 HSB8S2638ST 用）
#

#
#  SG実行用テンプレートファイル定義
#
TEMPLATE = h8s2638

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(TOPDIR)/config/$(CPU)/$(SYS)
COPTS := $(COPTS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(TOPDIR)/config/$(CPU)/$(SYS)
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS) sys_support.o
KERNEL_COBJS := $(KERNEL_COBJS) sys_config.o

#
#  外部RAMの有効／無効選択（有効時コメント解除）
#
USE_EXTRAM = true

#
#  外部RAM用
#
ifeq ($(USE_EXTRAM), true)
    COPTS		:= $(COPTS) -DUSE_EXT_RAM
endif

#
#  リンカスクリプトの定義
#
ifeq ($(USE_EXTRAM), true)
    LDSCRIPT = $(CPU)/$(SYS)/ext_ram_release.ld
else
    LDSCRIPT = $(CPU)/$(SYS)/nml_ram_release.ld
endif

